# Generated by Django 4.1.1 on 2022-09-23 01:33

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userpart', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer')], default='developer', max_length=16)),
                ('year', models.IntegerField()),
                ('image', models.TextField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentSeasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer')], default='developer', max_length=16)),
                ('image', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('test', 'Test'), ('interview', 'Interview')], default='test', max_length=16)),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruitmentseasons')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weightage', models.IntegerField()),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.rounds')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('marks', models.IntegerField()),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.sections')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('idle', 'Idle'), ('on_break', 'On Break')], default='idle', max_length=16)),
                ('panelist', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruitmentseasons')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('enrollment_no', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=16)),
                ('cg', models.DecimalField(decimal_places=2, max_digits=2)),
                ('current_round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.rounds')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('time_slot', models.CharField(max_length=64)),
                ('total_marks', models.IntegerField()),
                ('status', models.CharField(choices=[('not_notified', 'Not Notified'), ('notified', 'Notified'), ('waiting_room', 'In Waiting Room'), ('interview', 'In Interview'), ('done', 'Done')], default='not_notified', max_length=16)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.candidates')),
                ('interview_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.interviewpanel')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.rounds')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('remarks', models.TextField()),
                ('status', models.CharField(choices=[('checked', 'Checked'), ('unchecked', 'Unchecked')], default='unchecked', max_length=16)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.candidates')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.questions')),
            ],
        ),
    ]
