# Generated by Django 4.1.1 on 2022-09-22 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment_seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=16)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField()),
                ('type', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer')], default='developer', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('test', 'Test'), ('interview', 'Interview')], default='test', max_length=16)),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruitment_seasons')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='useremail',
            field=models.EmailField(max_length=255),
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weightage', models.IntegerField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.users')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.rounds')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('marks', models.IntegerField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.users')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.sections')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('enrollment_no', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=16)),
                ('cg', models.DecimalField(decimal_places=2, max_digits=2)),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.rounds')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruitment_seasons')),
            ],
        ),
    ]
