# Generated by Django 4.1.1 on 2022-09-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
