# Generated by Django 4.1.1 on 2022-09-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_recruitment_seasons_rounds_alter_users_useremail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('idle', 'Idle'), ('on_break', 'On Break')], default='idle', max_length=16)),
                ('panelist', models.ManyToManyField(to='recruiter.sections')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruitment_seasons')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('time_slot', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('not_notified', 'Not Notified'), ('notified', 'Notified'), ('waiting_room', 'In Waiting cRoom'), ('interview', 'In Interview'), ('done', 'Done')], default='not_notified', max_length=16)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.candidates')),
                ('interview_panel', models.ManyToManyField(to='recruiter.interview_panel')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.rounds')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('status', models.CharField(choices=[('checked', 'Checked'), ('unchecked', 'Unchecked')], default='unchecked', max_length=16)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.candidates')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.questions')),
            ],
        ),
    ]
