# Generated by Django 4.1.1 on 2022-09-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_users_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
