# Generated by Django 4.1.1 on 2022-09-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_remove_candidateprojectlink_taking_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemarks',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidateround',
            name='status',
            field=models.CharField(choices=[('not_notified', 'Not Notified'), ('notified', 'Notified'), ('waiting_room', 'In Waiting Room'), ('interview', 'In Interview'), ('done', 'Done')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='interviewpanel',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('occupied', 'Occupied'), ('idle', 'Idle'), ('on_break', 'On Break')], default='inactive', max_length=16),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
